# Generated by Django 4.1.4 on 2023-02-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Externallink',
        ),
    ]
