# Generated by Django 4.1.4 on 2023-02-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
