# Generated by Django 4.1.4 on 2023-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
